# Generated by Django 5.1 on 2025-03-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
    ]
